# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electricity', 'Electricity'), ('hvac', 'Heating / air conditioning'), ('elevator', 'Elevator'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('common_areas', 'Common areas'), ('noise', 'Noise / neighbourhood'), ('information', 'Information request'), ('suggestion', 'Comment or suggestion'), ('other', 'Other')], default='other', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open (awaiting assignment)'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved (awaiting requester confirmation)'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='properties.property')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Empty when the request concerns common areas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_round', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('requester_notice', models.CharField(blank=True, choices=[('DONE', 'Done'), ('NOT_DONE', 'Not done')], max_length=8, null=True)),
                ('requester_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('requester_comment', models.TextField(blank=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_assignments', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['service_request_id', 'resolution_round', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['property', 'status'], name='service_req_propert_f64d17_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['requester', 'status'], name='service_req_request_0ef896_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['unit'], name='service_req_unit_id_3b1996_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('current_round__gte', 1)), name='service_request_round_positive'),
        ),
        migrations.AddIndex(
            model_name='servicerequestassignment',
            index=models.Index(fields=['resolver', 'is_resolved'], name='service_req_resolve_dfe47f_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestassignment',
            constraint=models.UniqueConstraint(fields=('service_request', 'resolver', 'resolution_round'), name='unique_assignment_per_round'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestassignment',
            constraint=models.CheckConstraint(condition=models.Q(('requester_rating__isnull', True), models.Q(('requester_rating__gte', 1), ('requester_rating__lte', 5)), _connector='OR'), name='assignment_rating_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='servicerequestassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_resolved', False), ('resolved_at__isnull', False), _connector='OR'), name='assignment_resolved_has_timestamp'),
        ),
    ]
