# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuilding',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='properties.building'),
        ),
        migrations.AddField(
            model_name='userbuilding',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbuilding',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbuilding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersyndicat',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersyndicat',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersyndicat',
            name='syndicat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='properties.syndicat'),
        ),
        migrations.AddField(
            model_name='usersyndicat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'last_name'], name='accounts_us_is_acti_1cedd4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('deactivated_at__isnull', False), _connector='OR'), name='user_inactive_has_deactivation_date'),
        ),
        migrations.AddIndex(
            model_name='providerprofile',
            index=models.Index(fields=['service_type'], name='accounts_pr_service_09e729_idx'),
        ),
        migrations.AddIndex(
            model_name='userbuilding',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_5a3094_idx'),
        ),
        migrations.AddIndex(
            model_name='userbuilding',
            index=models.Index(fields=['building', 'is_active'], name='accounts_us_buildin_494349_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbuilding',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'building'), name='unique_active_user_building'),
        ),
        migrations.AddConstraint(
            model_name='userbuilding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='user_building_revoked_consistent'),
        ),
        migrations.AddIndex(
            model_name='userproperty',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_a652b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userproperty',
            index=models.Index(fields=['property', 'is_active'], name='accounts_us_propert_16833f_idx'),
        ),
        migrations.AddConstraint(
            model_name='userproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'property'), name='unique_active_user_property'),
        ),
        migrations.AddConstraint(
            model_name='userproperty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='user_property_revoked_consistent'),
        ),
        migrations.AddIndex(
            model_name='usersyndicat',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_5ae8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='usersyndicat',
            index=models.Index(fields=['syndicat', 'is_active'], name='accounts_us_syndica_569af3_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersyndicat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'syndicat'), name='unique_active_user_syndicat'),
        ),
        migrations.AddConstraint(
            model_name='usersyndicat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='user_syndicat_revoked_consistent'),
        ),
    ]
