# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("properties", "0003_deletion_cascades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbuilding",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="userproperty",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="usersyndicat",
            name="syndicat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="properties.syndicat",
            ),
        ),
    ]
