# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General information'), ('meeting', 'Meetings & assemblies'), ('maintenance', 'Maintenance work'), ('security', 'Security'), ('rules', 'Rules & policies'), ('financial', 'Financial information'), ('community', 'Community life'), ('emergency', 'Emergency')], default='general', max_length=16)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('admin', 'Administrators'), ('syndic', 'Syndics'), ('manager', 'Managers'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('provider', 'Service providers'), ('owner', 'Owners'), ('tenant', 'Tenants')], max_length=16), size=None)),
                ('published_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(blank=True, help_text='Optional narrowing of the target roles to one building.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='properties.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='properties.property')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['property', 'archived_at', '-published_at'], name='announcemen_propert_f3c891_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_roles__len__gt', 0)), name='announcement_has_target_roles'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('published_at')), _connector='OR'), name='announcement_expires_after_publication')],
            },
        ),
    ]
