# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
        ("properties", "0003_deletion_cascades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="building",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional narrowing of the target roles to one building.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="properties.property",
            ),
        ),
    ]
