# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representative_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='represented_promoter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('include_service_request', models.BooleanField(default=True)),
                ('include_announcements', models.BooleanField(default=True)),
                ('include_events', models.BooleanField(default=True)),
                ('include_amenities', models.BooleanField(default=True)),
                ('include_store', models.BooleanField(default=True)),
                ('include_library', models.BooleanField(default=True)),
                ('include_short_term_rental', models.BooleanField(default=True)),
                ('include_surveys', models.BooleanField(default=True)),
                ('include_marketplace', models.BooleanField(default=True)),
                ('include_visitor', models.BooleanField(default=True)),
                ('include_chat', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.promoter')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True)),
                ('floors_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='properties.property')),
            ],
            options={
                'ordering': ['property_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Syndicat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='syndicat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.syndicat'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House / villa'), ('office', 'Office'), ('commercial', 'Commercial space'), ('parking', 'Parking space'), ('storage', 'Storage'), ('other', 'Other')], default='apartment', max_length=16)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rooms_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.building')),
            ],
            options={
                'ordering': ['building_id', 'number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnitOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_share', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=16)),
                ('is_promoter_default', models.BooleanField(default=False, help_text="Automatic ownership held by the property's promoter.")),
                ('end_reason', models.CharField(blank=True, choices=[('SALE', 'Sold to a new owner'), ('DEPARTURE', 'Owner left (no registered acquirer)'), ('PROMOTER_CHANGE', 'Property promoter replaced'), ('CORRECTION', 'Administrative correction')], max_length=24)),
                ('acquisition_reference', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_ownerships', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='promoter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='promoter_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(models.F('property'), django.db.models.functions.text.Lower('name'), name='building_name_per_property'),
        ),
        migrations.AddConstraint(
            model_name='syndicat',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='syndicat_name_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['syndicat', 'is_active'], name='properties__syndica_4469dc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['promoter'], name='properties__promote_b9fd79_idx'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(models.F('syndicat'), django.db.models.functions.text.Lower('name'), name='property_name_per_syndicat'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_unit_number_per_building'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('area_sqm__isnull', True), ('area_sqm__gt', 0), _connector='OR'), name='unit_area_positive'),
        ),
        migrations.AddIndex(
            model_name='unitownership',
            index=models.Index(fields=['owner', 'unit', 'status'], name='properties__owner_i_b44183_idx'),
        ),
        migrations.AddIndex(
            model_name='unitownership',
            index=models.Index(fields=['unit', 'status'], name='properties__unit_id_e30713_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ownership_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), ('end_date__isnull', True)), models.Q(('status', 'TERMINATED'), ('end_date__isnull', False)), _connector='OR'), name='ownership_status_matches_end_date'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_share__isnull', True), models.Q(('ownership_share__gt', 0), ('ownership_share__lte', 100)), _connector='OR'), name='ownership_share_percentage'),
        ),
        migrations.AddConstraint(
            model_name='unitownership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('unit', 'owner'), name='unique_active_ownership_per_user_unit'),
        ),
    ]
