# Generated by Django 5.2.17 on 2026-09-24 23:29

import apps.properties.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="timezone",
            field=models.CharField(
                default=apps.properties.timezones.default_time_zone, max_length=64
            ),
        ),
    ]
