# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="syndicat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="properties.syndicat",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="unitownership",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="properties.unit",
            ),
        ),
    ]
