# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('real_estate_rental', 'Real estate for rent'), ('real_estate_sale', 'Real estate for sale'), ('various_offer', 'Various offers')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MAD', max_length=3)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('SOLD', 'Sold / rented'), ('ARCHIVED', 'Archived by the seller'), ('MODERATED', 'Taken down by moderation')], default='PUBLISHED', max_length=10)),
                ('published_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_reason', models.TextField(blank=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['status', 'category', '-published_at'], name='marketplace_status_d57887_idx'), models.Index(fields=['property', 'status'], name='marketplace_propert_93e3b5_idx'), models.Index(fields=['seller', 'status'], name='marketplace_seller__6a13d6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='listing_price_non_negative')],
            },
        ),
    ]
