# Generated by Django 5.2.17 on 2026-09-23 14:02

import apps.common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # GiST support, required by the exclusion constraints below.
        ('common', '0001_postgres_extensions'),
        ('leasing', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator_capacity', models.CharField(choices=[('TENANT', 'Tenant of the unit'), ('OWNER', 'Owner of the unit'), ('MANAGEMENT', 'Property management')], max_length=12)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Members on site'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_short_term_rentals', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(blank=True, help_text='Lease bounding the rental when declared by a tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='short_term_rentals', to='leasing.lease')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='short_term_rentals', to='properties.unit')),
            ],
            options={
                'ordering': ['-checkin_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShortTermRentalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('UNDISCLOSED', 'Undisclosed')], default='UNDISCLOSED', max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('id_document_number', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('short_term_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='short_term_rental.shorttermrental')),
            ],
            options={
                'ordering': ['short_term_rental_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shorttermrental',
            name='primary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='short_term_rental.shorttermrentalmember'),
        ),
        migrations.AddIndex(
            model_name='shorttermrental',
            index=models.Index(fields=['unit', 'status'], name='short_term__unit_id_e5a6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='shorttermrental',
            index=models.Index(fields=['initiated_by', 'status'], name='short_term__initiat_25a0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='shorttermrental',
            constraint=models.CheckConstraint(condition=models.Q(('checkout_date__gt', models.F('checkin_date'))), name='short_term_rental_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='shorttermrental',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('initiator_capacity', 'TENANT'), _negated=True), ('lease__isnull', False), _connector='OR'), name='short_term_rental_tenant_has_lease'),
        ),
        migrations.AddConstraint(
            model_name='shorttermrental',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('SCHEDULED', 'CHECKED_IN'))), expressions=[(apps.common.db.DateRange('checkin_date', 'checkout_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('unit', '=')], name='short_term_rental_no_overlap_per_unit'),
        ),
    ]
