# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0002_deletion_cascades"),
        ("properties", "0003_deletion_cascades"),
        ("short_term_rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorttermrental",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                help_text="Lease bounding the rental when declared by a tenant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_term_rentals",
                to="leasing.lease",
            ),
        ),
        migrations.AlterField(
            model_name="shorttermrental",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="short_term_rentals",
                to="properties.unit",
            ),
        ),
    ]
