# Generated by Django 5.2.17 on 2026-09-25 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_term_rental", "0002_deletion_cascades"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorttermrental",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_short_term_rentals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
