// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import {
  accountCreateRequestSchema,
  accountDeactivationRequestSchema,
  buildingAssignmentInputRequestSchema,
  emailChangeRequestSchema,
  loginRequestSchema,
  paginatedUserListSchema,
  passwordChangeRequestSchema,
  passwordResetRequestSchema,
  passwordSetRequestSchema,
  patchedProviderProfileRequestSchema,
  patchedUserProfileRequestSchema,
  providerProfileSchema,
  roleChangeRequestSchema,
  sessionContextSchema,
  tokenRefreshRequestSchema,
  tokenRefreshSchema,
  userBuildingSchema,
  userPropertySchema,
  userSchema,
  userSyndicatSchema,
  usersBuildingAssignmentsListQueryParamsSchema,
  usersListQueryParamsSchema,
  usersPropertyAssignmentsListQueryParamsSchema,
  usersSyndicatAssignmentsListQueryParamsSchema,
} from "../accounts";

/** Endpoints of the accounts module. */
export const accountsEndpoints = {
  authPasswordResetCreate: {
    method: "POST",
    path: "/api/v1/auth/password/reset/",
    tag: "Auth",
    auth: false,
    uiConfigStep: null,
    requiredHeaders: [],
    body: passwordResetRequestSchema,
    bodyType: "json",
    response: null,
    status: 202,
  },
  /** Completes an invitation or a reset (uid + token from the e-mail link). */
  authPasswordSetCreate: {
    method: "POST",
    path: "/api/v1/auth/password/set/",
    tag: "Auth",
    auth: false,
    uiConfigStep: null,
    requiredHeaders: [],
    body: passwordSetRequestSchema,
    bodyType: "json",
    response: null,
    status: 204,
  },
  /** Logs in and configures the session: the response is the `SessionContext`. */
  authTokenCreate: {
    method: "POST",
    path: "/api/v1/auth/token/",
    tag: "Auth",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: loginRequestSchema,
    bodyType: "json",
    response: sessionContextSchema,
    status: 200,
  },
  /**
   * Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  authTokenRefreshCreate: {
    method: "POST",
    path: "/api/v1/auth/token/refresh/",
    tag: "Auth",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: tokenRefreshRequestSchema,
    bodyType: "json",
    response: tokenRefreshSchema,
    status: 200,
  },
  buildingAssignmentsRevokeCreate: {
    method: "POST",
    path: "/api/v1/building-assignments/{assignment_id}/revoke/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ assignment_id: z.number().int() }),
    response: userBuildingSchema,
    status: 200,
  },
  propertyAssignmentsRevokeCreate: {
    method: "POST",
    path: "/api/v1/property-assignments/{assignment_id}/revoke/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ assignment_id: z.number().int() }),
    response: userPropertySchema,
    status: 200,
  },
  syndicatAssignmentsRevokeCreate: {
    method: "POST",
    path: "/api/v1/syndicat-assignments/{assignment_id}/revoke/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ assignment_id: z.number().int() }),
    response: userSyndicatSchema,
    status: 200,
  },
  /** Assigns a security or cleaning account to buildings of the selected property. */
  usersBuildingAssignmentsCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/building-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: ["X-Syndicat-Id"],
    pathParams: z.object({ user_id: z.string() }),
    body: buildingAssignmentInputRequestSchema,
    bodyType: "json",
    response: z.array(userBuildingSchema),
    status: 201,
  },
  /** The buildings a security or cleaning account works in. */
  usersBuildingAssignmentsList: {
    method: "GET",
    path: "/api/v1/users/{user_id}/building-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ user_id: z.string() }),
    queryParams: usersBuildingAssignmentsListQueryParamsSchema,
    response: z.array(userBuildingSchema),
    status: 200,
  },
  usersCreate: {
    method: "POST",
    path: "/api/v1/users/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: ["X-Syndicat-Id"],
    body: accountCreateRequestSchema,
    bodyType: "json",
    response: userSchema,
    status: 201,
  },
  /** Deactivates an account: it keeps its history but cannot sign in. */
  usersDeactivateCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/deactivate/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    body: accountDeactivationRequestSchema,
    bodyType: "json",
    response: userSchema,
    status: 200,
  },
  /** Closes the account: deactivation and erasure of personal data. */
  usersDestroy: {
    method: "DELETE",
    path: "/api/v1/users/{user_id}/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    response: null,
    status: 204,
  },
  /** Changes the login address. Holders confirm with their current password. */
  usersEmailCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/email/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    body: emailChangeRequestSchema,
    bodyType: "json",
    response: userSchema,
    status: 200,
  },
  /** Sends the invitation again, to an account that has not set its password. */
  usersInvitationCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/invitation/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    response: null,
    status: 202,
  },
  /** Accounts the actor may see, narrowed to the selected property when one is. */
  usersList: {
    method: "GET",
    path: "/api/v1/users/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: usersListQueryParamsSchema,
    response: paginatedUserListSchema,
    status: 200,
  },
  /** One account: its profile, and the closing of the account. */
  usersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/users/{user_id}/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    body: patchedUserProfileRequestSchema,
    bodyType: "json",
    response: userSchema,
    status: 200,
  },
  /** Only the holder changes their own password; someone else sends a new invitation. */
  usersPasswordCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/password/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    body: passwordChangeRequestSchema,
    bodyType: "json",
    response: null,
    status: 204,
  },
  /** Assigns a manager or a maintenance account to the selected property. */
  usersPropertyAssignmentsCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/property-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: ["X-Syndicat-Id"],
    pathParams: z.object({ user_id: z.string() }),
    response: z.array(userPropertySchema),
    status: 201,
  },
  /** The properties a manager or a maintenance account works on. */
  usersPropertyAssignmentsList: {
    method: "GET",
    path: "/api/v1/users/{user_id}/property-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ user_id: z.string() }),
    queryParams: usersPropertyAssignmentsListQueryParamsSchema,
    response: z.array(userPropertySchema),
    status: 200,
  },
  /** The complementary profile of a service provider account. */
  usersProviderProfilePartialUpdate: {
    method: "PATCH",
    path: "/api/v1/users/{user_id}/provider-profile/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    body: patchedProviderProfileRequestSchema,
    bodyType: "json",
    response: providerProfileSchema,
    status: 200,
  },
  /** The complementary profile of a service provider account. */
  usersProviderProfileRetrieve: {
    method: "GET",
    path: "/api/v1/users/{user_id}/provider-profile/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    response: providerProfileSchema,
    status: 200,
  },
  /** Puts a deactivated account back in service. */
  usersReactivateCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/reactivate/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    response: userSchema,
    status: 200,
  },
  /** One account: its profile, and the closing of the account. */
  usersRetrieve: {
    method: "GET",
    path: "/api/v1/users/{user_id}/",
    tag: "Users",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ user_id: z.string() }),
    response: userSchema,
    status: 200,
  },
  /**
   * The role is granted where the actor works: the selected syndicat for a
   * syndic, the selected property for the other roles.
   */
  usersRoleCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/role/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: ["X-Syndicat-Id"],
    pathParams: z.object({ user_id: z.string() }),
    body: roleChangeRequestSchema,
    bodyType: "json",
    response: userSchema,
    status: 200,
  },
  /** Assigns a syndic account to the selected syndicat. */
  usersSyndicatAssignmentsCreate: {
    method: "POST",
    path: "/api/v1/users/{user_id}/syndicat-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ user_id: z.string() }),
    response: z.array(userSyndicatSchema),
    status: 201,
  },
  /** The syndicats a syndic account runs. */
  usersSyndicatAssignmentsList: {
    method: "GET",
    path: "/api/v1/users/{user_id}/syndicat-assignments/",
    tag: "Roles & assignments",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ user_id: z.string() }),
    queryParams: usersSyndicatAssignmentsListQueryParamsSchema,
    response: z.array(userSyndicatSchema),
    status: 200,
  },
} as const;
