// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { amenitiesListQueryParamsSchema, amenitiesScheduleListQueryParamsSchema, amenityCreateRequestSchema, amenitySchema, amenitySlotSchema, bookingCreateRequestSchema, bookingDecisionRequestSchema, bookingSchema, bookingsListQueryParamsSchema, paginatedAmenityListSchema, paginatedBookingListSchema, patchedAmenityRequestSchema } from "../amenities";
import { actionReasonRequestSchema, bulkActionResultSchema, uploadFilesRequestSchema } from "../shared";

/** Endpoints of the amenities module. */
export const amenitiesEndpoints = {
  /** Bulk action (admin, syndic, manager): every booking of the selected property whose slot has ended is settled: a confirmed one becomes COMPLETED, one still pending is CANCELLED. */
  bookingsCompletePastCreate: {
    method: "POST",
    path: "/api/v1/bookings/complete-past/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    response: bulkActionResultSchema,
    status: 200,
  },
  amenitiesCreate: {
    method: "POST",
    path: "/api/v1/amenities/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: amenityCreateRequestSchema,
    bodyType: "json",
    response: amenitySchema,
    status: 201,
  },
  /** Deletes an amenity that was never booked. */
  amenitiesDestroy: {
    method: "DELETE",
    path: "/api/v1/amenities/{amenity_id}/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int() }),
    response: null,
    status: 204,
  },
  amenitiesImagesCreate: {
    method: "POST",
    path: "/api/v1/amenities/{amenity_id}/images/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: amenitySchema,
    status: 201,
  },
  amenitiesImagesDestroy: {
    method: "DELETE",
    path: "/api/v1/amenities/{amenity_id}/images/{attachment_id}/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int(), attachment_id: z.number().int() }),
    response: null,
    status: 204,
  },
  amenitiesList: {
    method: "GET",
    path: "/api/v1/amenities/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: amenitiesListQueryParamsSchema,
    response: paginatedAmenityListSchema,
    status: 200,
  },
  amenitiesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/amenities/{amenity_id}/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int() }),
    body: patchedAmenityRequestSchema,
    bodyType: "json",
    response: amenitySchema,
    status: 200,
  },
  amenitiesRetrieve: {
    method: "GET",
    path: "/api/v1/amenities/{amenity_id}/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int() }),
    response: amenitySchema,
    status: 200,
  },
  amenitiesScheduleList: {
    method: "GET",
    path: "/api/v1/amenities/{amenity_id}/schedule/",
    tag: "Amenities",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ amenity_id: z.number().int() }),
    queryParams: amenitiesScheduleListQueryParamsSchema,
    response: z.array(amenitySlotSchema),
    status: 200,
  },
  bookingsCancelCreate: {
    method: "POST",
    path: "/api/v1/bookings/{booking_id}/cancel/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ booking_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: bookingSchema,
    status: 200,
  },
  bookingsCreate: {
    method: "POST",
    path: "/api/v1/bookings/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: bookingCreateRequestSchema,
    bodyType: "json",
    response: bookingSchema,
    status: 201,
  },
  bookingsDecisionCreate: {
    method: "POST",
    path: "/api/v1/bookings/{booking_id}/decision/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ booking_id: z.number().int() }),
    body: bookingDecisionRequestSchema,
    bodyType: "json",
    response: bookingSchema,
    status: 200,
  },
  /** Permanently deletes the booking and its conversation. */
  bookingsDestroy: {
    method: "DELETE",
    path: "/api/v1/bookings/{booking_id}/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ booking_id: z.number().int() }),
    response: null,
    status: 204,
  },
  bookingsList: {
    method: "GET",
    path: "/api/v1/bookings/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: bookingsListQueryParamsSchema,
    response: paginatedBookingListSchema,
    status: 200,
  },
  bookingsRetrieve: {
    method: "GET",
    path: "/api/v1/bookings/{booking_id}/",
    tag: "Bookings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ booking_id: z.number().int() }),
    response: bookingSchema,
    status: 200,
  },
} as const;
