// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { announcementCreateRequestSchema, announcementSchema, announcementsListQueryParamsSchema, paginatedAnnouncementListSchema, patchedAnnouncementRequestSchema } from "../announcements";
import { uploadFilesRequestSchema } from "../shared";

/** Endpoints of the announcements module. */
export const announcementsEndpoints = {
  /** Archives the announcement: it leaves the feed but the record stays. */
  announcementsArchiveCreate: {
    method: "POST",
    path: "/api/v1/announcements/{announcement_id}/archive/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int() }),
    response: announcementSchema,
    status: 200,
  },
  announcementsCreate: {
    method: "POST",
    path: "/api/v1/announcements/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: announcementCreateRequestSchema,
    bodyType: "multipart",
    response: announcementSchema,
    status: 201,
  },
  /** Erases the announcement for good, with its files and the notifications already delivered (administrators and syndics). To archive it instead (keeping the record), use /archive/. */
  announcementsDestroy: {
    method: "DELETE",
    path: "/api/v1/announcements/{announcement_id}/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int() }),
    response: null,
    status: 204,
  },
  announcementsFilesCreate: {
    method: "POST",
    path: "/api/v1/announcements/{announcement_id}/files/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: announcementSchema,
    status: 201,
  },
  announcementsFilesDestroy: {
    method: "DELETE",
    path: "/api/v1/announcements/{announcement_id}/files/{attachment_id}/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int(), attachment_id: z.number().int() }),
    response: null,
    status: 204,
  },
  announcementsList: {
    method: "GET",
    path: "/api/v1/announcements/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: announcementsListQueryParamsSchema,
    response: paginatedAnnouncementListSchema,
    status: 200,
  },
  announcementsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/announcements/{announcement_id}/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int() }),
    body: patchedAnnouncementRequestSchema,
    bodyType: "json",
    response: announcementSchema,
    status: 200,
  },
  announcementsRetrieve: {
    method: "GET",
    path: "/api/v1/announcements/{announcement_id}/",
    tag: "Announcements",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ announcement_id: z.number().int() }),
    response: announcementSchema,
    status: 200,
  },
} as const;
