// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { chatMessageCreateRequestSchema, chatMessageSchema, chatRoomOpenRequestSchema, chatRoomSchema, chatRoomsListQueryParamsSchema, chatRoomsMessagesListQueryParamsSchema, paginatedChatMessageListSchema, paginatedChatRoomListSchema, patchedChatMessageRequestSchema } from "../chat";

/** Endpoints of the chat module. */
export const chatEndpoints = {
  chatRoomsCreate: {
    method: "POST",
    path: "/api/v1/chat/rooms/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: chatRoomOpenRequestSchema,
    bodyType: "json",
    response: chatRoomSchema,
    status: 200,
  },
  chatRoomsList: {
    method: "GET",
    path: "/api/v1/chat/rooms/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: chatRoomsListQueryParamsSchema,
    response: paginatedChatRoomListSchema,
    status: 200,
  },
  chatRoomsMessagesCreate: {
    method: "POST",
    path: "/api/v1/chat/rooms/{room_id}/messages/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ room_id: z.number().int() }),
    body: chatMessageCreateRequestSchema,
    bodyType: "multipart",
    response: chatMessageSchema,
    status: 201,
  },
  /** Deletes the message and its media (author, or property management). */
  chatRoomsMessagesDestroy: {
    method: "DELETE",
    path: "/api/v1/chat/rooms/{room_id}/messages/{message_id}/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ message_id: z.number().int(), room_id: z.number().int() }),
    response: null,
    status: 204,
  },
  chatRoomsMessagesList: {
    method: "GET",
    path: "/api/v1/chat/rooms/{room_id}/messages/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ room_id: z.number().int() }),
    queryParams: chatRoomsMessagesListQueryParamsSchema,
    response: paginatedChatMessageListSchema,
    status: 200,
  },
  /** Edit or delete one message of the conversation. */
  chatRoomsMessagesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/chat/rooms/{room_id}/messages/{message_id}/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ message_id: z.number().int(), room_id: z.number().int() }),
    body: patchedChatMessageRequestSchema,
    bodyType: "json",
    response: chatMessageSchema,
    status: 200,
  },
  chatRoomsReadCreate: {
    method: "POST",
    path: "/api/v1/chat/rooms/{room_id}/read/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ room_id: z.number().int() }),
    response: null,
    status: 204,
  },
  chatRoomsRetrieve: {
    method: "GET",
    path: "/api/v1/chat/rooms/{room_id}/",
    tag: "Chat",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ room_id: z.number().int() }),
    response: chatRoomSchema,
    status: 200,
  },
} as const;
