// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { eventCreateRequestSchema, eventSchema, eventsListQueryParamsSchema, paginatedEventListSchema, patchedEventRequestSchema } from "../events";
import { actionReasonRequestSchema, bulkActionResultSchema, uploadFilesRequestSchema } from "../shared";

/** Endpoints of the events module. */
export const eventsEndpoints = {
  /** Bulk action (admin, syndic, manager): completes every scheduled event of the selected property that has ended. */
  eventsCompletePastCreate: {
    method: "POST",
    path: "/api/v1/events/complete-past/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    response: bulkActionResultSchema,
    status: 200,
  },
  /** Archives the event: it leaves the feed but the record stays. */
  eventsArchiveCreate: {
    method: "POST",
    path: "/api/v1/events/{event_id}/archive/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    response: eventSchema,
    status: 200,
  },
  eventsCancelCreate: {
    method: "POST",
    path: "/api/v1/events/{event_id}/cancel/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: eventSchema,
    status: 200,
  },
  eventsCreate: {
    method: "POST",
    path: "/api/v1/events/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: eventCreateRequestSchema,
    bodyType: "multipart",
    response: eventSchema,
    status: 201,
  },
  /** Erases the event for good, with its files and the notifications already delivered (administrators and syndics). To archive it instead (keeping the record), use /archive/. */
  eventsDestroy: {
    method: "DELETE",
    path: "/api/v1/events/{event_id}/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    response: null,
    status: 204,
  },
  eventsFilesCreate: {
    method: "POST",
    path: "/api/v1/events/{event_id}/files/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: eventSchema,
    status: 201,
  },
  eventsFilesDestroy: {
    method: "DELETE",
    path: "/api/v1/events/{event_id}/files/{attachment_id}/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ attachment_id: z.number().int(), event_id: z.number().int() }),
    response: null,
    status: 204,
  },
  eventsList: {
    method: "GET",
    path: "/api/v1/events/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: eventsListQueryParamsSchema,
    response: paginatedEventListSchema,
    status: 200,
  },
  eventsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/events/{event_id}/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    body: patchedEventRequestSchema,
    bodyType: "json",
    response: eventSchema,
    status: 200,
  },
  eventsRetrieve: {
    method: "GET",
    path: "/api/v1/events/{event_id}/",
    tag: "Events",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ event_id: z.number().int() }),
    response: eventSchema,
    status: 200,
  },
} as const;
