// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { leaseComponentStateInputRequestSchema, leaseComponentStateSchema, leaseCreateRequestSchema, leaseMemberDepartureRequestSchema, leaseMemberInputRequestSchema, leaseMemberSchema, leaseSchema, leaseTerminationRequestSchema, leasesLeaseComponentStatesListQueryParamsSchema, leasesListQueryParamsSchema, paginatedLeaseComponentStateListSchema, paginatedLeaseListSchema, patchedLeaseComponentStateRequestSchema, patchedLeaseMemberRequestSchema, patchedLeaseRequestSchema } from "../leasing";
import { actionReasonRequestSchema, bulkActionResultSchema, patchedUploadFileRequestSchema, uploadFilesRequestSchema } from "../shared";

/** Endpoints of the leasing module. */
export const leasingEndpoints = {
  /** Bulk action (admin, syndic, manager): terminates at term every active lease of the selected property whose end date has passed. */
  leasesExpireDueCreate: {
    method: "POST",
    path: "/api/v1/leases/expire-due/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    response: bulkActionResultSchema,
    status: 200,
  },
  leaseMembersDepartureCreate: {
    method: "POST",
    path: "/api/v1/lease-members/{member_id}/departure/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ member_id: z.number().int() }),
    body: leaseMemberDepartureRequestSchema,
    bodyType: "json",
    response: leaseMemberSchema,
    status: 200,
  },
  leaseMembersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/lease-members/{member_id}/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ member_id: z.number().int() }),
    body: patchedLeaseMemberRequestSchema,
    bodyType: "json",
    response: leaseMemberSchema,
    status: 200,
  },
  leaseMembersProofOfAddressPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/lease-members/{member_id}/proof-of-address/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ member_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: leaseMemberSchema,
    status: 200,
  },
  leaseMembersProofOfIdentityPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/lease-members/{member_id}/proof-of-identity/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ member_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: leaseMemberSchema,
    status: 200,
  },
  leaseMembersRetrieve: {
    method: "GET",
    path: "/api/v1/lease-members/{member_id}/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ member_id: z.number().int() }),
    response: leaseMemberSchema,
    status: 200,
  },
  leasesCancelCreate: {
    method: "POST",
    path: "/api/v1/leases/{lease_id}/cancel/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: leaseSchema,
    status: 200,
  },
  leasesCreate: {
    method: "POST",
    path: "/api/v1/leases/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: leaseCreateRequestSchema,
    bodyType: "json",
    response: leaseSchema,
    status: 201,
  },
  /** Permanently deletes the lease, its members and its inspections. */
  leasesDestroy: {
    method: "DELETE",
    path: "/api/v1/leases/{lease_id}/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    response: null,
    status: 204,
  },
  leasesLeaseComponentStatesCreate: {
    method: "POST",
    path: "/api/v1/leases/{lease_id}/lease-component-states/",
    tag: "Inspections",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    body: leaseComponentStateInputRequestSchema,
    bodyType: "multipart",
    response: leaseComponentStateSchema,
    status: 201,
  },
  /** Deletes a line recorded by mistake. */
  leasesLeaseComponentStatesDestroy: {
    method: "DELETE",
    path: "/api/v1/leases/{lease_id}/lease-component-states/{lease_component_state_id}/",
    tag: "Inspections",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_component_state_id: z.number().int(), lease_id: z.number().int() }),
    response: null,
    status: 204,
  },
  leasesLeaseComponentStatesFilesCreate: {
    method: "POST",
    path: "/api/v1/leases/{lease_id}/lease-component-states/{lease_component_state_id}/files/",
    tag: "Inspections",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_component_state_id: z.number().int(), lease_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: leaseComponentStateSchema,
    status: 201,
  },
  leasesLeaseComponentStatesList: {
    method: "GET",
    path: "/api/v1/leases/{lease_id}/lease-component-states/",
    tag: "Inspections",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    queryParams: leasesLeaseComponentStatesListQueryParamsSchema,
    response: paginatedLeaseComponentStateListSchema,
    status: 200,
  },
  /** One line of an inspection, always read through its lease. */
  leasesLeaseComponentStatesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/leases/{lease_id}/lease-component-states/{lease_component_state_id}/",
    tag: "Inspections",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_component_state_id: z.number().int(), lease_id: z.number().int() }),
    body: patchedLeaseComponentStateRequestSchema,
    bodyType: "json",
    response: leaseComponentStateSchema,
    status: 200,
  },
  leasesList: {
    method: "GET",
    path: "/api/v1/leases/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: leasesListQueryParamsSchema,
    response: paginatedLeaseListSchema,
    status: 200,
  },
  leasesMembersCreate: {
    method: "POST",
    path: "/api/v1/leases/{lease_id}/members/",
    tag: "Lease members",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    body: leaseMemberInputRequestSchema,
    bodyType: "json",
    response: leaseMemberSchema,
    status: 201,
  },
  leasesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/leases/{lease_id}/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    body: patchedLeaseRequestSchema,
    bodyType: "json",
    response: leaseSchema,
    status: 200,
  },
  leasesRetrieve: {
    method: "GET",
    path: "/api/v1/leases/{lease_id}/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    response: leaseSchema,
    status: 200,
  },
  leasesTerminateCreate: {
    method: "POST",
    path: "/api/v1/leases/{lease_id}/terminate/",
    tag: "Leases",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ lease_id: z.number().int() }),
    body: leaseTerminationRequestSchema,
    bodyType: "json",
    response: leaseSchema,
    status: 200,
  },
} as const;
