// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { libraryDocumentCreateRequestSchema, libraryDocumentSchema, libraryDocumentsListQueryParamsSchema, libraryFolderCreateRequestSchema, libraryFolderSchema, libraryFoldersListQueryParamsSchema, paginatedLibraryDocumentListSchema, paginatedLibraryFolderListSchema, patchedLibraryDocumentRequestSchema, patchedLibraryFolderRequestSchema } from "../library";
import { patchedUploadFileRequestSchema } from "../shared";

/** Endpoints of the library module. */
export const libraryEndpoints = {
  libraryDocumentsCreate: {
    method: "POST",
    path: "/api/v1/library/documents/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: libraryDocumentCreateRequestSchema,
    bodyType: "multipart",
    response: libraryDocumentSchema,
    status: 201,
  },
  libraryDocumentsDestroy: {
    method: "DELETE",
    path: "/api/v1/library/documents/{document_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ document_id: z.number().int() }),
    response: null,
    status: 204,
  },
  libraryDocumentsFilePartialUpdate: {
    method: "PATCH",
    path: "/api/v1/library/documents/{document_id}/file/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ document_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: libraryDocumentSchema,
    status: 200,
  },
  libraryDocumentsList: {
    method: "GET",
    path: "/api/v1/library/documents/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: libraryDocumentsListQueryParamsSchema,
    response: paginatedLibraryDocumentListSchema,
    status: 200,
  },
  libraryDocumentsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/library/documents/{document_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ document_id: z.number().int() }),
    body: patchedLibraryDocumentRequestSchema,
    bodyType: "json",
    response: libraryDocumentSchema,
    status: 200,
  },
  libraryDocumentsRetrieve: {
    method: "GET",
    path: "/api/v1/library/documents/{document_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ document_id: z.number().int() }),
    response: libraryDocumentSchema,
    status: 200,
  },
  libraryFoldersCreate: {
    method: "POST",
    path: "/api/v1/library/folders/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: libraryFolderCreateRequestSchema,
    bodyType: "json",
    response: libraryFolderSchema,
    status: 201,
  },
  libraryFoldersDestroy: {
    method: "DELETE",
    path: "/api/v1/library/folders/{folder_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ folder_id: z.number().int() }),
    response: null,
    status: 204,
  },
  libraryFoldersList: {
    method: "GET",
    path: "/api/v1/library/folders/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: libraryFoldersListQueryParamsSchema,
    response: paginatedLibraryFolderListSchema,
    status: 200,
  },
  libraryFoldersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/library/folders/{folder_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ folder_id: z.number().int() }),
    body: patchedLibraryFolderRequestSchema,
    bodyType: "json",
    response: libraryFolderSchema,
    status: 200,
  },
  libraryFoldersRetrieve: {
    method: "GET",
    path: "/api/v1/library/folders/{folder_id}/",
    tag: "Library",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ folder_id: z.number().int() }),
    response: libraryFolderSchema,
    status: 200,
  },
} as const;
