// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { marketplaceListingCreateRequestSchema, marketplaceListingImagesRequestSchema, marketplaceListingModerationRequestSchema, marketplaceListingSchema, marketplaceListingsListQueryParamsSchema, paginatedMarketplaceListingListSchema, patchedMarketplaceListingRequestSchema } from "../marketplace";

/** Endpoints of the marketplace module. */
export const marketplaceEndpoints = {
  /** The seller puts the ad away; the record stays (delete erases it). */
  marketplaceListingsArchiveCreate: {
    method: "POST",
    path: "/api/v1/marketplace/listings/{listing_id}/archive/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    response: marketplaceListingSchema,
    status: 200,
  },
  marketplaceListingsCreate: {
    method: "POST",
    path: "/api/v1/marketplace/listings/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: marketplaceListingCreateRequestSchema,
    bodyType: "multipart",
    response: marketplaceListingSchema,
    status: 201,
  },
  /** Deletes the listing (seller or moderator). */
  marketplaceListingsDestroy: {
    method: "DELETE",
    path: "/api/v1/marketplace/listings/{listing_id}/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    response: null,
    status: 204,
  },
  marketplaceListingsImagesCreate: {
    method: "POST",
    path: "/api/v1/marketplace/listings/{listing_id}/images/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    body: marketplaceListingImagesRequestSchema,
    bodyType: "multipart",
    response: marketplaceListingSchema,
    status: 201,
  },
  marketplaceListingsImagesDestroy: {
    method: "DELETE",
    path: "/api/v1/marketplace/listings/{listing_id}/images/{attachment_id}/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ attachment_id: z.number().int(), listing_id: z.number().int() }),
    response: null,
    status: 204,
  },
  marketplaceListingsList: {
    method: "GET",
    path: "/api/v1/marketplace/listings/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: marketplaceListingsListQueryParamsSchema,
    response: paginatedMarketplaceListingListSchema,
    status: 200,
  },
  marketplaceListingsModerationCreate: {
    method: "POST",
    path: "/api/v1/marketplace/listings/{listing_id}/moderation/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    body: marketplaceListingModerationRequestSchema,
    bodyType: "json",
    response: marketplaceListingSchema,
    status: 200,
  },
  marketplaceListingsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/marketplace/listings/{listing_id}/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    body: patchedMarketplaceListingRequestSchema,
    bodyType: "json",
    response: marketplaceListingSchema,
    status: 200,
  },
  marketplaceListingsRetrieve: {
    method: "GET",
    path: "/api/v1/marketplace/listings/{listing_id}/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    response: marketplaceListingSchema,
    status: 200,
  },
  /** The item was sold: the ad leaves the catalogue. */
  marketplaceListingsSoldCreate: {
    method: "POST",
    path: "/api/v1/marketplace/listings/{listing_id}/sold/",
    tag: "Marketplace",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ listing_id: z.number().int() }),
    response: marketplaceListingSchema,
    status: 200,
  },
} as const;
