// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { inboxNotificationSchema, notificationPreferenceSchema, notificationUnreadCountSchema, notificationsListQueryParamsSchema, notificationsMarkedReadSchema, paginatedInboxNotificationListSchema, patchedNotificationPreferenceRequestSchema, pushTokenRegisterRequestSchema, pushTokenSchema } from "../notifications";

/** Endpoints of the notifications module. */
export const notificationsEndpoints = {
  notificationsList: {
    method: "GET",
    path: "/api/v1/notifications/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: notificationsListQueryParamsSchema,
    response: paginatedInboxNotificationListSchema,
    status: 200,
  },
  notificationsPreferencesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/notifications/preferences/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: patchedNotificationPreferenceRequestSchema,
    bodyType: "json",
    response: notificationPreferenceSchema,
    status: 200,
  },
  notificationsPreferencesRetrieve: {
    method: "GET",
    path: "/api/v1/notifications/preferences/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    response: notificationPreferenceSchema,
    status: 200,
  },
  notificationsPushTokensCreate: {
    method: "POST",
    path: "/api/v1/notifications/push-tokens/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: pushTokenRegisterRequestSchema,
    bodyType: "json",
    response: pushTokenSchema,
    status: 200,
  },
  notificationsPushTokensDestroy: {
    method: "DELETE",
    path: "/api/v1/notifications/push-tokens/{device_id}/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ device_id: z.string() }),
    response: null,
    status: 204,
  },
  notificationsReadAllCreate: {
    method: "POST",
    path: "/api/v1/notifications/read-all/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    response: notificationsMarkedReadSchema,
    status: 200,
  },
  notificationsReadCreate: {
    method: "POST",
    path: "/api/v1/notifications/{notification_id}/read/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ notification_id: z.number().int() }),
    response: inboxNotificationSchema,
    status: 200,
  },
  notificationsUnreadCountRetrieve: {
    method: "GET",
    path: "/api/v1/notifications/unread-count/",
    tag: "Notifications",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    response: notificationUnreadCountSchema,
    status: 200,
  },
} as const;
