// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { buildingInputRequestSchema, buildingSchema, buildingsUnitsListQueryParamsSchema, ownershipCoOwnerRequestSchema, ownershipEndRequestSchema, ownershipSchema, ownershipTransferRequestSchema, paginatedBuildingListSchema, paginatedOwnershipListSchema, paginatedPromoterListSchema, paginatedPropertyListSchema, paginatedSyndicatListSchema, paginatedUnitListSchema, patchedBuildingRequestSchema, patchedPromoterRequestSchema, patchedPropertyFeaturesRequestSchema, patchedPropertyRequestSchema, patchedSyndicatRequestSchema, patchedUnitRequestSchema, promoterChangeRequestSchema, promoterInputRequestSchema, promoterSchema, promotersListQueryParamsSchema, propertiesBuildingsListQueryParamsSchema, propertiesListQueryParamsSchema, propertyInputRequestSchema, propertySchema, propertyStatisticsSchema, syndicatInputRequestSchema, syndicatSchema, syndicatsListQueryParamsSchema, uiConfigPropertiesListQueryParamsSchema, uiConfigPropertySchema, uiConfigSyndicatSchema, uiConfigSyndicatsListQueryParamsSchema, unitInputRequestSchema, unitSchema, unitsMineListQueryParamsSchema, unitsOwnershipsListQueryParamsSchema } from "../properties";
import { patchedUploadFileRequestSchema } from "../shared";

/** Endpoints of the properties module. */
export const propertiesEndpoints = {
  /** Deletes an empty building. */
  buildingsDestroy: {
    method: "DELETE",
    path: "/api/v1/buildings/{building_id}/",
    tag: "Buildings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ building_id: z.number().int() }),
    response: null,
    status: 204,
  },
  buildingsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/buildings/{building_id}/",
    tag: "Buildings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ building_id: z.number().int() }),
    body: patchedBuildingRequestSchema,
    bodyType: "json",
    response: buildingSchema,
    status: 200,
  },
  buildingsRetrieve: {
    method: "GET",
    path: "/api/v1/buildings/{building_id}/",
    tag: "Buildings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ building_id: z.number().int() }),
    response: buildingSchema,
    status: 200,
  },
  buildingsUnitsCreate: {
    method: "POST",
    path: "/api/v1/buildings/{building_id}/units/",
    tag: "Units",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ building_id: z.number().int() }),
    body: unitInputRequestSchema,
    bodyType: "json",
    response: unitSchema,
    status: 201,
  },
  buildingsUnitsList: {
    method: "GET",
    path: "/api/v1/buildings/{building_id}/units/",
    tag: "Units",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ building_id: z.number().int() }),
    queryParams: buildingsUnitsListQueryParamsSchema,
    response: paginatedUnitListSchema,
    status: 200,
  },
  /** Erases a ledger line recorded by mistake; the unit never stays without an owner. */
  ownershipsDestroy: {
    method: "DELETE",
    path: "/api/v1/ownerships/{ownership_id}/",
    tag: "Ownership",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ ownership_id: z.number().int() }),
    response: null,
    status: 204,
  },
  ownershipsEndCreate: {
    method: "POST",
    path: "/api/v1/ownerships/{ownership_id}/end/",
    tag: "Ownership",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ ownership_id: z.number().int() }),
    body: ownershipEndRequestSchema,
    bodyType: "json",
    response: ownershipSchema,
    status: 200,
  },
  promotersCreate: {
    method: "POST",
    path: "/api/v1/promoters/",
    tag: "Promoters",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: promoterInputRequestSchema,
    bodyType: "json",
    response: promoterSchema,
    status: 201,
  },
  /** Deletes a promoter that develops no property. */
  promotersDestroy: {
    method: "DELETE",
    path: "/api/v1/promoters/{promoter_id}/",
    tag: "Promoters",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ promoter_id: z.number().int() }),
    response: null,
    status: 204,
  },
  promotersList: {
    method: "GET",
    path: "/api/v1/promoters/",
    tag: "Promoters",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: promotersListQueryParamsSchema,
    response: paginatedPromoterListSchema,
    status: 200,
  },
  promotersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/promoters/{promoter_id}/",
    tag: "Promoters",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ promoter_id: z.number().int() }),
    body: patchedPromoterRequestSchema,
    bodyType: "json",
    response: promoterSchema,
    status: 200,
  },
  promotersRetrieve: {
    method: "GET",
    path: "/api/v1/promoters/{promoter_id}/",
    tag: "Promoters",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ promoter_id: z.number().int() }),
    response: promoterSchema,
    status: 200,
  },
  propertiesBuildingsCreate: {
    method: "POST",
    path: "/api/v1/properties/{property_id}/buildings/",
    tag: "Buildings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    body: buildingInputRequestSchema,
    bodyType: "json",
    response: buildingSchema,
    status: 201,
  },
  propertiesBuildingsList: {
    method: "GET",
    path: "/api/v1/properties/{property_id}/buildings/",
    tag: "Buildings",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    queryParams: propertiesBuildingsListQueryParamsSchema,
    response: paginatedBuildingListSchema,
    status: 200,
  },
  propertiesCreate: {
    method: "POST",
    path: "/api/v1/properties/",
    tag: "Properties",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: propertyInputRequestSchema,
    bodyType: "json",
    response: propertySchema,
    status: 201,
  },
  /** Deletes an empty property (409 while it still holds content). */
  propertiesDestroy: {
    method: "DELETE",
    path: "/api/v1/properties/{property_id}/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    response: null,
    status: 204,
  },
  propertiesFeaturesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/properties/{property_id}/features/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    body: patchedPropertyFeaturesRequestSchema,
    bodyType: "json",
    response: propertySchema,
    status: 200,
  },
  propertiesList: {
    method: "GET",
    path: "/api/v1/properties/",
    tag: "Properties",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: propertiesListQueryParamsSchema,
    response: paginatedPropertyListSchema,
    status: 200,
  },
  propertiesLogoPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/properties/{property_id}/logo/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: propertySchema,
    status: 200,
  },
  propertiesPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/properties/{property_id}/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    body: patchedPropertyRequestSchema,
    bodyType: "json",
    response: propertySchema,
    status: 200,
  },
  propertiesPromoterCreate: {
    method: "POST",
    path: "/api/v1/properties/{property_id}/promoter/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    body: promoterChangeRequestSchema,
    bodyType: "json",
    response: propertySchema,
    status: 200,
  },
  propertiesRetrieve: {
    method: "GET",
    path: "/api/v1/properties/{property_id}/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    response: propertySchema,
    status: 200,
  },
  propertiesStatisticsRetrieve: {
    method: "GET",
    path: "/api/v1/properties/{property_id}/statistics/",
    tag: "Properties",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ property_id: z.number().int() }),
    response: propertyStatisticsSchema,
    status: 200,
  },
  syndicatsCreate: {
    method: "POST",
    path: "/api/v1/syndicats/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    body: syndicatInputRequestSchema,
    bodyType: "json",
    response: syndicatSchema,
    status: 201,
  },
  /** Deletes an empty syndicat (409 while it still holds properties). */
  syndicatsDestroy: {
    method: "DELETE",
    path: "/api/v1/syndicats/{syndicat_id}/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ syndicat_id: z.number().int() }),
    response: null,
    status: 204,
  },
  syndicatsList: {
    method: "GET",
    path: "/api/v1/syndicats/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: syndicatsListQueryParamsSchema,
    response: paginatedSyndicatListSchema,
    status: 200,
  },
  syndicatsLogoPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/syndicats/{syndicat_id}/logo/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ syndicat_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: syndicatSchema,
    status: 200,
  },
  syndicatsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/syndicats/{syndicat_id}/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ syndicat_id: z.number().int() }),
    body: patchedSyndicatRequestSchema,
    bodyType: "json",
    response: syndicatSchema,
    status: 200,
  },
  syndicatsRetrieve: {
    method: "GET",
    path: "/api/v1/syndicats/{syndicat_id}/",
    tag: "Syndicats",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    pathParams: z.object({ syndicat_id: z.number().int() }),
    response: syndicatSchema,
    status: 200,
  },
  /**
   * Second configuration page: the properties of the syndicat just chosen,
   * which the client carries in `X-Syndicat-Id`.
   */
  uiConfigPropertiesList: {
    method: "GET",
    path: "/api/v1/ui-config/properties/",
    tag: "UI configuration",
    auth: true,
    uiConfigStep: "property",
    requiredHeaders: ["X-Syndicat-Id"],
    queryParams: uiConfigPropertiesListQueryParamsSchema,
    response: z.array(uiConfigPropertySchema),
    status: 200,
  },
  /**
   * First configuration page: the syndicats the account may open.
   *
   * Resolved from assignments, so a syndicat without any property yet is listed.
   */
  uiConfigSyndicatsList: {
    method: "GET",
    path: "/api/v1/ui-config/syndicats/",
    tag: "UI configuration",
    auth: true,
    uiConfigStep: "syndicat",
    requiredHeaders: [],
    queryParams: uiConfigSyndicatsListQueryParamsSchema,
    response: z.array(uiConfigSyndicatSchema),
    status: 200,
  },
  /** Deletes a unit that was never leased nor sold. */
  unitsDestroy: {
    method: "DELETE",
    path: "/api/v1/units/{unit_id}/",
    tag: "Units",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    response: null,
    status: 204,
  },
  unitsMineList: {
    method: "GET",
    path: "/api/v1/units/mine/",
    tag: "Units",
    auth: true,
    uiConfigStep: null,
    requiredHeaders: [],
    queryParams: unitsMineListQueryParamsSchema,
    response: paginatedUnitListSchema,
    status: 200,
  },
  unitsOwnershipsCoOwnersCreate: {
    method: "POST",
    path: "/api/v1/units/{unit_id}/ownerships/co-owners/",
    tag: "Ownership",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    body: ownershipCoOwnerRequestSchema,
    bodyType: "json",
    response: ownershipSchema,
    status: 201,
  },
  unitsOwnershipsList: {
    method: "GET",
    path: "/api/v1/units/{unit_id}/ownerships/",
    tag: "Ownership",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    queryParams: unitsOwnershipsListQueryParamsSchema,
    response: paginatedOwnershipListSchema,
    status: 200,
  },
  unitsOwnershipsTransferCreate: {
    method: "POST",
    path: "/api/v1/units/{unit_id}/ownerships/transfer/",
    tag: "Ownership",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    body: ownershipTransferRequestSchema,
    bodyType: "json",
    response: z.array(ownershipSchema),
    status: 201,
  },
  unitsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/units/{unit_id}/",
    tag: "Units",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    body: patchedUnitRequestSchema,
    bodyType: "json",
    response: unitSchema,
    status: 200,
  },
  unitsRetrieve: {
    method: "GET",
    path: "/api/v1/units/{unit_id}/",
    tag: "Units",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ unit_id: z.number().int() }),
    response: unitSchema,
    status: 200,
  },
} as const;
