// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { paginatedServiceRequestListSchema, serviceRequestAssignRequestSchema, serviceRequestAssignmentSchema, serviceRequestCreateRequestSchema, serviceRequestFeedbackRequestSchema, serviceRequestResolveRequestSchema, serviceRequestSchema, serviceRequestsListQueryParamsSchema } from "../service-requests";
import { actionReasonRequestSchema, uploadFilesRequestSchema } from "../shared";

/** Endpoints of the service-requests module. */
export const serviceRequestsEndpoints = {
  serviceRequestsAssignmentsCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/assignments/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    body: serviceRequestAssignRequestSchema,
    bodyType: "json",
    response: z.array(serviceRequestAssignmentSchema),
    status: 201,
  },
  serviceRequestsAssignmentsList: {
    method: "GET",
    path: "/api/v1/service-requests/{request_id}/assignments/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    response: z.array(serviceRequestAssignmentSchema),
    status: 200,
  },
  serviceRequestsCancelCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/cancel/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: serviceRequestSchema,
    status: 200,
  },
  serviceRequestsCloseCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/close/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    response: serviceRequestSchema,
    status: 200,
  },
  serviceRequestsCreate: {
    method: "POST",
    path: "/api/v1/service-requests/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: serviceRequestCreateRequestSchema,
    bodyType: "multipart",
    response: serviceRequestSchema,
    status: 201,
  },
  /** Permanently deletes the request, its rounds and its conversation. */
  serviceRequestsDestroy: {
    method: "DELETE",
    path: "/api/v1/service-requests/{request_id}/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    response: null,
    status: 204,
  },
  serviceRequestsFeedbackCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/feedback/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    body: serviceRequestFeedbackRequestSchema,
    bodyType: "json",
    response: serviceRequestSchema,
    status: 200,
  },
  serviceRequestsFilesCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/files/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: serviceRequestSchema,
    status: 201,
  },
  serviceRequestsFilesDestroy: {
    method: "DELETE",
    path: "/api/v1/service-requests/{request_id}/files/{attachment_id}/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ attachment_id: z.number().int(), request_id: z.number().int() }),
    response: null,
    status: 204,
  },
  serviceRequestsList: {
    method: "GET",
    path: "/api/v1/service-requests/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: serviceRequestsListQueryParamsSchema,
    response: paginatedServiceRequestListSchema,
    status: 200,
  },
  serviceRequestsResolveCreate: {
    method: "POST",
    path: "/api/v1/service-requests/{request_id}/resolve/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    body: serviceRequestResolveRequestSchema,
    bodyType: "multipart",
    response: serviceRequestAssignmentSchema,
    status: 200,
  },
  serviceRequestsRetrieve: {
    method: "GET",
    path: "/api/v1/service-requests/{request_id}/",
    tag: "Service requests",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ request_id: z.number().int() }),
    response: serviceRequestSchema,
    status: 200,
  },
} as const;
