// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { actionReasonRequestSchema, bulkActionResultSchema, patchedUploadFileRequestSchema } from "../shared";
import { paginatedShortTermRentalListSchema, patchedShortTermRentalMemberRequestSchema, shortTermRentalCreateRequestSchema, shortTermRentalMemberCreateRequestSchema, shortTermRentalMemberSchema, shortTermRentalRescheduleRequestSchema, shortTermRentalSchema, shortTermRentalsListQueryParamsSchema } from "../short-term-rentals";

/** Endpoints of the short-term-rentals module. */
export const shortTermRentalsEndpoints = {
  /** Bulk action (admin, syndic, manager): completes every scheduled or checked-in rental of the selected property whose checkout date has passed. */
  shortTermRentalsCompletePastCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/complete-past/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    response: bulkActionResultSchema,
    status: 200,
  },
  shortTermRentalMembersDestroy: {
    method: "DELETE",
    path: "/api/v1/short-term-rental-members/{short_term_rental_member_id}/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_member_id: z.number().int() }),
    response: null,
    status: 204,
  },
  shortTermRentalMembersIdCardPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/short-term-rental-members/{short_term_rental_member_id}/id-card/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_member_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: shortTermRentalMemberSchema,
    status: 200,
  },
  shortTermRentalMembersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/short-term-rental-members/{short_term_rental_member_id}/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_member_id: z.number().int() }),
    body: patchedShortTermRentalMemberRequestSchema,
    bodyType: "json",
    response: shortTermRentalMemberSchema,
    status: 200,
  },
  shortTermRentalsCancelCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/cancel/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: shortTermRentalSchema,
    status: 200,
  },
  shortTermRentalsCheckInCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/check-in/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    response: shortTermRentalSchema,
    status: 200,
  },
  shortTermRentalsCompleteCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/complete/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    response: shortTermRentalSchema,
    status: 200,
  },
  shortTermRentalsCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: shortTermRentalCreateRequestSchema,
    bodyType: "json",
    response: shortTermRentalSchema,
    status: 201,
  },
  /** Permanently deletes the rental and its members. */
  shortTermRentalsDestroy: {
    method: "DELETE",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    response: null,
    status: 204,
  },
  shortTermRentalsList: {
    method: "GET",
    path: "/api/v1/short-term-rentals/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: shortTermRentalsListQueryParamsSchema,
    response: paginatedShortTermRentalListSchema,
    status: 200,
  },
  shortTermRentalsMembersCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/members/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    body: shortTermRentalMemberCreateRequestSchema,
    bodyType: "json",
    response: shortTermRentalMemberSchema,
    status: 201,
  },
  shortTermRentalsMembersList: {
    method: "GET",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/members/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    response: z.array(shortTermRentalMemberSchema),
    status: 200,
  },
  shortTermRentalsRescheduleCreate: {
    method: "POST",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/reschedule/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    body: shortTermRentalRescheduleRequestSchema,
    bodyType: "json",
    response: shortTermRentalSchema,
    status: 200,
  },
  shortTermRentalsRetrieve: {
    method: "GET",
    path: "/api/v1/short-term-rentals/{short_term_rental_id}/",
    tag: "Short-term rentals",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ short_term_rental_id: z.number().int() }),
    response: shortTermRentalSchema,
    status: 200,
  },
} as const;
