// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { actionReasonRequestSchema, uploadFilesRequestSchema } from "../shared";
import { actionNoteRequestSchema, orderCreateRequestSchema, orderSchema, paginatedOrderListSchema, paginatedProductListSchema, patchedProductRequestSchema, productCreateRequestSchema, productSchema, storeOrdersListQueryParamsSchema, storeProductsListQueryParamsSchema } from "../store";

/** Endpoints of the store module. */
export const storeEndpoints = {
  storeOrdersCancelCreate: {
    method: "POST",
    path: "/api/v1/store/orders/{order_id}/cancel/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ order_id: z.number().int() }),
    body: actionReasonRequestSchema,
    bodyType: "json",
    response: orderSchema,
    status: 200,
  },
  storeOrdersConfirmCreate: {
    method: "POST",
    path: "/api/v1/store/orders/{order_id}/confirm/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ order_id: z.number().int() }),
    body: actionNoteRequestSchema,
    bodyType: "json",
    response: orderSchema,
    status: 200,
  },
  storeOrdersCreate: {
    method: "POST",
    path: "/api/v1/store/orders/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: orderCreateRequestSchema,
    bodyType: "json",
    response: orderSchema,
    status: 201,
  },
  storeOrdersDeliverCreate: {
    method: "POST",
    path: "/api/v1/store/orders/{order_id}/deliver/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ order_id: z.number().int() }),
    body: actionNoteRequestSchema,
    bodyType: "json",
    response: orderSchema,
    status: 200,
  },
  /** Permanently deletes the order; reserved stock is restored. */
  storeOrdersDestroy: {
    method: "DELETE",
    path: "/api/v1/store/orders/{order_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ order_id: z.number().int() }),
    response: null,
    status: 204,
  },
  storeOrdersList: {
    method: "GET",
    path: "/api/v1/store/orders/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: storeOrdersListQueryParamsSchema,
    response: paginatedOrderListSchema,
    status: 200,
  },
  storeOrdersRetrieve: {
    method: "GET",
    path: "/api/v1/store/orders/{order_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ order_id: z.number().int() }),
    response: orderSchema,
    status: 200,
  },
  storeProductsCreate: {
    method: "POST",
    path: "/api/v1/store/products/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: productCreateRequestSchema,
    bodyType: "json",
    response: productSchema,
    status: 201,
  },
  /** Deletes a product that was never ordered. */
  storeProductsDestroy: {
    method: "DELETE",
    path: "/api/v1/store/products/{product_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ product_id: z.number().int() }),
    response: null,
    status: 204,
  },
  storeProductsImagesCreate: {
    method: "POST",
    path: "/api/v1/store/products/{product_id}/images/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ product_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: productSchema,
    status: 201,
  },
  storeProductsImagesDestroy: {
    method: "DELETE",
    path: "/api/v1/store/products/{product_id}/images/{attachment_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ attachment_id: z.number().int(), product_id: z.number().int() }),
    response: null,
    status: 204,
  },
  storeProductsList: {
    method: "GET",
    path: "/api/v1/store/products/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: storeProductsListQueryParamsSchema,
    response: paginatedProductListSchema,
    status: 200,
  },
  storeProductsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/store/products/{product_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ product_id: z.number().int() }),
    body: patchedProductRequestSchema,
    bodyType: "json",
    response: productSchema,
    status: 200,
  },
  storeProductsRetrieve: {
    method: "GET",
    path: "/api/v1/store/products/{product_id}/",
    tag: "Store",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ product_id: z.number().int() }),
    response: productSchema,
    status: 200,
  },
} as const;
