// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { patchedUploadFileRequestSchema } from "../shared";
import { paginatedVisitorListSchema, patchedVisitorRequestSchema, visitorCreateRequestSchema, visitorDepartureRequestSchema, visitorSchema, visitorsListQueryParamsSchema } from "../visitors";

/** Endpoints of the visitors module. */
export const visitorsEndpoints = {
  visitorsCreate: {
    method: "POST",
    path: "/api/v1/visitors/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: visitorCreateRequestSchema,
    bodyType: "multipart",
    response: visitorSchema,
    status: 201,
  },
  visitorsDepartureCreate: {
    method: "POST",
    path: "/api/v1/visitors/{visitor_id}/departure/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ visitor_id: z.number().int() }),
    body: visitorDepartureRequestSchema,
    bodyType: "json",
    response: visitorSchema,
    status: 200,
  },
  /** Deletes an entry logged by mistake (management only). */
  visitorsDestroy: {
    method: "DELETE",
    path: "/api/v1/visitors/{visitor_id}/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ visitor_id: z.number().int() }),
    response: null,
    status: 204,
  },
  visitorsIdCardPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/visitors/{visitor_id}/id-card/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ visitor_id: z.number().int() }),
    body: patchedUploadFileRequestSchema,
    bodyType: "multipart",
    response: visitorSchema,
    status: 200,
  },
  visitorsList: {
    method: "GET",
    path: "/api/v1/visitors/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: visitorsListQueryParamsSchema,
    response: paginatedVisitorListSchema,
    status: 200,
  },
  visitorsPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/visitors/{visitor_id}/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ visitor_id: z.number().int() }),
    body: patchedVisitorRequestSchema,
    bodyType: "json",
    response: visitorSchema,
    status: 200,
  },
  visitorsRetrieve: {
    method: "GET",
    path: "/api/v1/visitors/{visitor_id}/",
    tag: "Visitors",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ visitor_id: z.number().int() }),
    response: visitorSchema,
    status: 200,
  },
} as const;
