// Contracts of the backend API, kept in sync with its OpenAPI schema (see README).
import { z } from "zod";
import { uploadFilesRequestSchema } from "../shared";
import { paginatedWorkOrderListSchema, patchedWorkOrderRequestSchema, workOrderCreateRequestSchema, workOrderSchema, workOrderTransitionRequestSchema, workOrdersListQueryParamsSchema } from "../work-orders";

/** Endpoints of the work-orders module. */
export const workOrdersEndpoints = {
  workOrdersCreate: {
    method: "POST",
    path: "/api/v1/work-orders/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    body: workOrderCreateRequestSchema,
    bodyType: "multipart",
    response: workOrderSchema,
    status: 201,
  },
  /** Permanently deletes the work order and its files. */
  workOrdersDestroy: {
    method: "DELETE",
    path: "/api/v1/work-orders/{work_order_id}/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ work_order_id: z.number().int() }),
    response: null,
    status: 204,
  },
  workOrdersFilesCreate: {
    method: "POST",
    path: "/api/v1/work-orders/{work_order_id}/files/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ work_order_id: z.number().int() }),
    body: uploadFilesRequestSchema,
    bodyType: "multipart",
    response: workOrderSchema,
    status: 201,
  },
  workOrdersList: {
    method: "GET",
    path: "/api/v1/work-orders/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    queryParams: workOrdersListQueryParamsSchema,
    response: paginatedWorkOrderListSchema,
    status: 200,
  },
  workOrdersPartialUpdate: {
    method: "PATCH",
    path: "/api/v1/work-orders/{work_order_id}/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ work_order_id: z.number().int() }),
    body: patchedWorkOrderRequestSchema,
    bodyType: "json",
    response: workOrderSchema,
    status: 200,
  },
  workOrdersRetrieve: {
    method: "GET",
    path: "/api/v1/work-orders/{work_order_id}/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ work_order_id: z.number().int() }),
    response: workOrderSchema,
    status: 200,
  },
  workOrdersTransitionsCreate: {
    method: "POST",
    path: "/api/v1/work-orders/{work_order_id}/transitions/",
    tag: "Work orders",
    auth: true,
    uiConfigStep: "dashboard",
    requiredHeaders: ["X-Syndicat-Id", "X-Property-Id"],
    pathParams: z.object({ work_order_id: z.number().int() }),
    body: workOrderTransitionRequestSchema,
    bodyType: "json",
    response: workOrderSchema,
    status: 200,
  },
} as const;
