# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_deletion_cascades"),
        ("work_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_orders",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_orders",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_orders",
                to="properties.unit",
            ),
        ),
    ]
