# Generated by Django 5.2.17 on 2026-09-23 14:02

import apps.common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # GiST support, required by the exclusion constraints below.
        ('common', '0001_postgres_extensions'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('rules', models.TextField(blank=True)),
                ('booking_mode', models.CharField(choices=[('EXCLUSIVE', 'Exclusive slot (one booking at a time)'), ('SHARED', 'Shared (concurrent bookings up to capacity)')], default='EXCLUSIVE', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('requires_approval', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('min_duration_minutes', models.PositiveIntegerField(default=30)),
                ('max_duration_minutes', models.PositiveIntegerField(default=240)),
                ('max_advance_days', models.PositiveIntegerField(default=60)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat fee per booking.', max_digits=12)),
                ('security_fee', models.DecimalField(decimal_places=2, default=0, help_text='Security cost charged per booking.', max_digits=12)),
                ('hourly_price', models.DecimalField(decimal_places=2, default=0, help_text='Price per hour of use; 0 for a free amenity.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='properties.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amenities', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['property_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('is_exclusive', models.BooleanField()),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('booker_note', models.TextField(blank=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='amenities.amenity')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='amenity_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.CheckConstraint(condition=models.Q(('max_duration_minutes__gte', models.F('min_duration_minutes'))), name='amenity_duration_bounds'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opening_time__isnull', True), ('closing_time__isnull', True)), models.Q(('opening_time__isnull', False), ('closing_time__isnull', False), ('closing_time__gt', models.F('opening_time'))), _connector='OR'), name='amenity_opening_hours_consistent'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(models.F('property'), django.db.models.functions.text.Lower('name'), name='amenity_name_per_property'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0), ('security_fee__gte', 0), ('hourly_price__gte', 0)), name='amenity_prices_non_negative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['amenity', 'status', 'start_datetime'], name='amenities_b_amenity_37246b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booker', 'status'], name='amenities_b_booker__bee9fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='booking_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gte', 1)), name='booking_party_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_exclusive', True), ('status__in', ('PENDING', 'CONFIRMED'))), expressions=[(apps.common.db.DateTimeRange('start_datetime', 'end_datetime', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('amenity', '=')], name='booking_no_overlap_on_exclusive_amenity'),
        ),
    ]
