# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0001_initial"),
        ("properties", "0003_deletion_cascades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenities",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amenities",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="amenity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="amenities.amenity",
            ),
        ),
    ]
