# Generated by Django 5.2.17 on 2026-09-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amenities", "0003_user_deletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending approval"),
                    ("CONFIRMED", "Confirmed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
