# Generated by Django 5.2.17 on 2026-09-23 14:02

import apps.common.models.attachments
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_postgres_extensions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('syndicat_logo', 'Syndicat logo'), ('property_logo', 'Property logo'), ('announcement', 'Announcement files'), ('event', 'Event files'), ('survey', 'Survey files'), ('library_document', 'Library document file'), ('amenity', 'Amenity images'), ('product', 'Store product images'), ('marketplace_listing', 'Marketplace listing images'), ('service_request', 'Service request files'), ('service_request_resolution', 'Resolution evidence of a service request round'), ('work_order', 'Work order files'), ('lease_component_state', 'Inspection files'), ('lease_member_identity', 'Lease member proof of identity'), ('lease_member_address', 'Lease member proof of address'), ('visitor_id_card', 'Visitor identity card'), ('short_term_rental_member_id_card', 'Short-term rental member identity card'), ('chat_message', 'Chat message file')], max_length=40)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('file', models.FileField(max_length=255, upload_to=apps.common.models.attachments.attachment_upload_to)),
                ('mime_type', models.CharField(max_length=127)),
                ('size', models.PositiveBigIntegerField(help_text='Bytes.')),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='attachment_entity_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entity_type__in', ('chat_message', 'lease_member_address', 'lease_member_identity', 'library_document', 'property_logo', 'short_term_rental_member_id_card', 'syndicat_logo', 'visitor_id_card'))), fields=('entity_type', 'entity_id'), name='attachment_single_file_per_entity'), models.CheckConstraint(condition=models.Q(('size__gt', 0)), name='attachment_size_positive')],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='common_audi_content_9f3cd1_idx'), models.Index(fields=['actor', 'created_at'], name='common_audi_actor_i_b31395_idx'), models.Index(fields=['property', 'created_at'], name='common_audi_propert_450d75_idx'), models.Index(fields=['action'], name='common_audi_action_354598_idx')],
            },
        ),
    ]
