# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('visit_reason', models.CharField(blank=True, max_length=200)),
                ('vehicle_plate', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('ARRIVED', 'On site'), ('LEFT', 'Left'), ('DENIED', 'Entry denied')], max_length=8)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='properties.property')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['property', 'status', '-created_at'], name='visitors_vi_propert_18e801_idx'), models.Index(fields=['unit', '-created_at'], name='visitors_vi_unit_id_ce0d0e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'ARRIVED'), ('arrived_at__isnull', False), ('left_at__isnull', True)), models.Q(('status', 'LEFT'), ('arrived_at__isnull', False), ('left_at__gte', models.F('arrived_at'))), models.Q(('status', 'DENIED'), ('arrived_at__isnull', True), ('left_at__isnull', True)), _connector='OR'), name='visitor_status_timestamps_consistent')],
            },
        ),
    ]
