# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_deletion_cascades"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surveys",
                to="properties.property",
            ),
        ),
        migrations.AlterField(
            model_name="surveyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.surveyquestion",
            ),
        ),
        migrations.AlterField(
            model_name="surveyanswer",
            name="selected_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.surveyoption",
            ),
        ),
    ]
