# Generated by Django 5.2.17 on 2026-09-23 14:02

import apps.common.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # GiST support, required by the exclusion constraints below.
        ('common', '0001_postgres_extensions'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='NULL = open-ended / tacit renewal.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('contract_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terminated_on', models.DateField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, choices=[('TERM_REACHED', 'Contract term reached'), ('TENANT_NOTICE', 'Notice given by tenant'), ('LANDLORD_NOTICE', 'Notice given by landlord'), ('MUTUAL_AGREEMENT', 'Mutual agreement'), ('BREACH', 'Breach of contract'), ('OTHER', 'Other')], max_length=24)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeaseComponentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=8)),
                ('on_check', models.CharField(choices=[('IN', 'Move-in inspection'), ('OUT', 'Move-out inspection')], max_length=4)),
                ('on_check_date', models.DateField()),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_component_states', to='leasing.lease')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lease_id', 'on_check', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('is_signatory', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=80)),
                ('vehicles_info', models.JSONField(blank=True, default=list)),
                ('pets_info', models.JSONField(blank=True, default=list)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('departure_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='leasing.lease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lease_id', 'joined_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit', 'status'], name='leasing_lea_unit_id_b958a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='lease_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TERMINATED'), _negated=True), ('terminated_on__isnull', False), _connector='OR'), name='lease_terminated_has_date'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='lease_cancelled_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('contract_reference__isnull', False), models.Q(('contract_reference', ''), _negated=True)), fields=('contract_reference',), name='lease_contract_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'ACTIVE')), expressions=[(apps.common.db.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_lower=True, inclusive_upper=True)), '&&'), ('unit', '=')], name='lease_no_overlapping_active_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='leasecomponentstate',
            constraint=models.UniqueConstraint(models.F('lease'), models.F('on_check'), django.db.models.functions.text.Lower('name'), name='unique_component_per_inspection'),
        ),
        migrations.AddIndex(
            model_name='leasemember',
            index=models.Index(fields=['user', 'left_at'], name='leasing_lea_user_id_24eca5_idx'),
        ),
        migrations.AddIndex(
            model_name='leasemember',
            index=models.Index(fields=['lease', 'left_at'], name='leasing_lea_lease_i_d20060_idx'),
        ),
        migrations.AddConstraint(
            model_name='leasemember',
            constraint=models.UniqueConstraint(fields=('lease', 'user'), name='unique_lease_member'),
        ),
        migrations.AddConstraint(
            model_name='leasemember',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='lease_member_left_after_joined'),
        ),
    ]
