# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leasing", "0001_initial"),
        ("properties", "0003_deletion_cascades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leases",
                to="properties.unit",
            ),
        ),
        migrations.AlterField(
            model_name="leasemember",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="leasing.lease",
            ),
        ),
    ]
