# Generated by Django 5.2.17 on 2026-09-23 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_push', models.BooleanField(default=True)),
                ('enabled_email', models.BooleanField(default=True)),
                ('service_request_enabled', models.BooleanField(default=True)),
                ('announcements_enabled', models.BooleanField(default=True)),
                ('events_enabled', models.BooleanField(default=True)),
                ('bookings_enabled', models.BooleanField(default=True)),
                ('store_enabled', models.BooleanField(default=True)),
                ('library_enabled', models.BooleanField(default=True)),
                ('short_term_rental_enabled', models.BooleanField(default=True)),
                ('surveys_enabled', models.BooleanField(default=True)),
                ('marketplace_enabled', models.BooleanField(default=True)),
                ('visitors_enabled', models.BooleanField(default=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'E-mail'), ('PUSH', 'Push')], max_length=8)),
                ('notification_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed (gave up)')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_6d08f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=191)),
                ('expo_push_token', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('deactivated_reason', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_33f549_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_push_token_per_user_device'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('expo_push_token',), name='unique_active_expo_token')],
            },
        ),
        migrations.CreateModel(
            name='InboxNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('account', 'Account'), ('property', 'Property administration'), ('leasing', 'Leasing'), ('service_request', 'Service requests'), ('work_order', 'Work orders'), ('announcement', 'Announcements'), ('event', 'Events'), ('booking', 'Amenity bookings'), ('store', 'Store'), ('library', 'Library'), ('short_term_rental', 'Short-term rentals'), ('survey', 'Surveys'), ('marketplace', 'Marketplace'), ('visitor', 'Visitors'), ('chat', 'Chat')], max_length=32)),
                ('notification_type', models.CharField(help_text='e.g. service_request.created', max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_ed9fd0_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_746af7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_read', False), ('read_at__isnull', True)), models.Q(('is_read', True), ('read_at__isnull', False)), _connector='OR'), name='inbox_read_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='RecipientSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('matched_roles', models.JSONField(default=list, help_text='The target roles the user had when the snapshot was taken.')),
                ('snapshotted_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='notificatio_content_857f19_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'user'), name='unique_snapshot_recipient')],
            },
        ),
    ]
