# Generated by Django 5.2.17 on 2026-09-24 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("properties", "0003_deletion_cascades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="properties.property",
            ),
        ),
    ]
